### ISSUE TITLE
Allocate tokens before stopping a consumer chain

### ISSUE THREAD

**Issue by insumity** [cosmos/interchain-security#2094]
## Problem

Currently if a consumer chain is stopped/removed, the rewards sent to this consumer chain might not be given to the consumer validators. This is because the reward distribution [takes place after](https://github.com/cosmos/interchain-security/blob/3e7cd06035bb8863778001b7b77ae57a436222fb/x/ccv/provider/module.go#L172) the consumer chain has been removed. This issue is about investigating whether we should distribute the rewards before the chain stops.

**Comment by ukane-philemon** [comment]
> ## Problem
> 
> Currently if a consumer chain is stopped/removed, the rewards sent to this consumer chain might not be given to the consumer validators. This is because the reward distribution [takes place after](https://github.com/cosmos/interchain-security/blob/3e7cd06035bb8863778001b7b77ae57a436222fb/x/ccv/provider/module.go#L172) the consumer chain has been removed. This issue is about investigating whether we should distribute the rewards before the chain stops.

Is it possible to have an intermediary state to allow for the distribution of rewards before connections are dropped due to stopping the chains?

```
am.keeper.BeginBlockMCR(sdkCtx) // Mark Chain for removal.
am.keeper.BeginBlockRD(sdkCtx) // Reward distribution
am.keeper.BeginBlockCCR(sdkCtx) // Consumer Chains Removal
```

**Comment by mpoke** [comment]
@insumity this is fixed by ICS 6.0.0, right? The new behavior is to first stop a chain and then after the unbonding period elapses remove its state. Could you please confirm that's the case?

**Comment by insumity** [comment]
@mpoke Indeed, this is the case. A chain is first stopped and after unbonding period, its state is partially deleted. During this unbonding period, the consumer chain can still get rewards. This issue is not relevant anymore.
